---
title: "wk2_prac_coding"
author: "chris"
date: "2021/11/17"
output: html_document
---

```{r library}
library(here)
library(sf)
library(tidyverse)
library(janitor)
```

```{r read file}
LondonDataOSK <- read.csv(here::here('data',
                                     'LondonData.csv'),
                          header = TRUE,sep=',',encoding = 'latin1')

LondonData <- read_csv("https://data.london.gov.uk/download/ward-profiles-and-atlas/772d2d64-e8c6-46cb-86f9-e52b4c7851bc/ward-profiles-excel-version.csv", 
                       locale = locale(encoding = "latin1"),
                       na = "n/a")
```

```{r}
Datatypelist <- LondonData %>% 
  clean_names()%>%
  summarise_all(class) %>%
  pivot_longer(everything(), 
               names_to="All_variables", 
               values_to="Variable_class")

Datatypelist
```


```{r }
LondonBoroughs <- LondonData[626:658,]#method1
  
LondonBoroughs <- LondonData%>%       #method2 
  slice(626:658)

Femalelifeexp <- LondonData%>%
  filter(`Female life expectancy -2009-13`>90)

LondonBoroughs <- LondonData%>%
  filter(str_detect(`New code`, "^E09"))

LondonBoroughs%>%
  dplyr::select(`Ward name`)%>%
  print()

LondonBoroughs <- LondonBoroughs%>%
  distinct()
```



```{r selecting columns}
LondonBoroughs_manualcols <- LondonBoroughs[,c(1,19,20,21)] #method1

LondonBoroughs_dplyrcols <- LondonBoroughs%>%  #method2
  dplyr::select(c(1,19,20,21))

LondonBoroughs_contains <- LondonBoroughs%>%
  dplyr::select(contains('expectancy'),
                contains('obese - 2011/12 to 2013/14'),
                contains('Ward name'),
                contains('out-of-work'))

LondonBoroughs_contains2 <- LondonBoroughs%>%
  clean_names()%>%
  dplyr::select(contains('expectancy'),
                contains('obese_2011/12_to_2013/14'),
                contains('Ward_name'),
                contains('out_of_work'))
```

```{r renaming columns}
library(janitor)
LondonBoroughs <- LondonBoroughs%>%
  clean_names()%>%
  dplyr::rename(Borough='ward_name')

LondonBoroughs <- LondonBoroughs%>%
  clean_names(.,case='big_camel')
```

```{r}
Life_expectancy <- LondonBoroughs%>%
  clean_names()%>%
  mutate(averagelifeexpectancy=(female_life_expectancy2009_13 +
                                  male_life_expectancy2009_13)/2)%>%
  mutate(normalisedlifeexpectancy=averagelifeexpectancy/
           mean(averagelifeexpectancy))%>%
  select(new_code,
         borough,
         averagelifeexpectancy,
         normalisedlifeexpectancy)%>%
  arrange(desc(normalisedlifeexpectancy))

slice_head(Life_expectancy,n=5)
slice_tail(Life_expectancy,n=5)
```

```{r}
Life_expectancy2 <- Life_expectancy%>%
  mutate(UKcompare =case_when(averagelifeexpectancy>81.6 ~ 'above UK average',
                              TRUE ~ 'below UK average'))
Life_expectancy2
```

```{r}
Life_expectancy2_group <- Life_expectancy2%>%
  mutate(UKdiff=averagelifeexpectancy-81.6)%>%
  group_by(UKcompare)%>%
  summarise(range=max(UKdiff)-min(UKdiff),count=n(),Average=mean(UKdiff))

```

```{r}
Life_expectancy3 <- Life_expectancy%>%
  mutate(UKdiff = averagelifeexpectancy-81.16)%>%
  mutate(across(where(is.numeric),round,3))%>%
  mutate(across(UKdiff,round,0))%>%
  mutate(UKcompare = case_when(averagelifeexpectancy>=81 ~
                                 str_c('equal or above UK average by',
                                       UKdiff,
                                       'years',
                                       sep=' '),
                               TRUE ~ str_c('below UK average by',
                                            UKdiff,
                                            'years',
                                            sep=' ')))%>%
  group_by(UKcompare)%>%
  summarise(count=n())

```

```{r}
Life_expectancy4 <- Life_expectancy%>%
  mutate(UKdiff = averagelifeexpectancy-81.16)%>%
  mutate(across(where(is.numeric),round,3))%>%
  mutate(across(UKdiff,round,0))
```

```{r}
 plot(LondonBoroughs$MaleLifeExpectancy2009_13,
      LondonBoroughs$PercentChildrenInReceptionYearWhoAreObese2011_12To2013_14)
```


```{r pimp my graph}
library(plotly)
plot_ly(LondonBoroughs,
        x=~male_life_expectancy2009_13,
        y=~percent_children_in_reception_year_who_are_obese2011_12to2013_14,
        text=~borough,
        type='scatter',
        mode='markers')
```


#spatial data in r

```{r library}
library(maptools)
library(RColorBrewer)
library(classInt)
library(sp)
library(rgeos)
library(tmap)
library(tmaptools)
library(sf)
library(rgdal)
library(geojsonio)
```
```{r}
#method1
EW <- st_read("https://opendata.arcgis.com/datasets/8edafbe3276d4b56aec60991cbddda50_2.geojson")
#method2
#EW <- st_read(here::here('data',
                        #'Local_Authority_Districts_(December_2015)_Boundaries.geojson' ))

```

```{r}
EW <- st_read(here::here('data',
                         'Local_Authority_Districts_(December_2015)_Boundaries',
                         'Local_Authority_Districts_(December_2015)_Boundaries.shp'))
```


```{r}
LondonMap <- EW%>%
  filter(str_detect(lad15cd,'^E09'))

qtm(LondonMap)
```

```{r ATTRIBUTE DATA}
LondonData <- clean_names(LondonData)

BoroughDataMap <- EW%>%
  clean_names()%>%
  filter(str_detect(lad15cd,'^E09'))%>%
  merge(.,
        LondonData,
        by.x='lad15cd',
        by.y='new_code',
        no.dups=TRUE)%>%
  distinct(.,lad15cd,
           .keep_all = TRUE)

BoroughDataMap2 <- EW%>%
  clean_names()%>%
  filter(str_detect(lad15cd, "^E09"))%>%
  left_join(.,
            LondonData,
            by=c('lad15cd'='new_code'))
```

```{r simple mapping}
library(tmap)
library(tmaptools)
tmap_mode('plot')
qtm(BoroughDataMap,
    fill = 'rate_of_job_seekers_allowance_jsa_claimants_2015')
```


```{r}
tmaplondon <- BoroughDataMap%>%
  st_bbox(.)%>%
  tmaptools::read_osm(.,type='osm',zoom=NULL)
```

```{r}
tmap_mode("plot")

tm_shape(tmaplondon)+
tm_rgb()+
tm_shape(BoroughDataMap) + 
tm_polygons("rate_of_job_seekers_allowance_jsa_claimants_2015", 
        style="jenks",
        palette="YlOrBr",
        midpoint=NA,
        title="Rate per 1,000 people",
        alpha = 0.5) + 
  tm_compass(position = c("left", "bottom"),type = "arrow") + 
  tm_scale_bar(position = c("left", "bottom")) +
  tm_layout(title = "Job seekers' Allowance Claimants", legend.position = c("right", "bottom"))
```

```{r}
Life_expectancy4map <- EW%>%
  merge(.,
        Life_expectancy4,
        by.x='lad15cd',
        by.y='new_code',
        no.dups=TRUE)%>%
  distinct(.,lad15cd,
           .keep_all = TRUE)

tmap_mode("plot")
tm_shape(tmaplondon)+
tm_rgb()+
tm_shape(Life_expectancy4map) + 
tm_polygons("UKdiff", 
        style="pretty",
        palette="Blues",
        midpoint=NA,
        title="Number of years",
        alpha = 0.5) + 
  tm_compass(position = c("left", "bottom"),type = "arrow") + 
  tm_scale_bar(position = c("left", "bottom")) +
  tm_layout(title = "Different in life expectancy", legend.position = c("right", "bottom"))
```


```{r tidying data}
flytipping <- read_csv("https://data.london.gov.uk/download/fly-tipping-incidents/536278ff-a391-4f20-bc79-9e705c9b3ec0/fly-tipping-borough.csv")


flytipping1 <- read_csv("https://data.london.gov.uk/download/fly-tipping-incidents/536278ff-a391-4f20-bc79-9e705c9b3ec0/fly-tipping-borough.csv", 
                       col_types = cols(
                         code = col_character(),
                         area = col_character(),
                         year = col_character(),
                         total_incidents = col_number(),
                         total_action_taken = col_number(),
                         warning_letters = col_number(),
                         fixed_penalty_notices = col_number(),
                         statutory_notices = col_number(),
                         formal_cautions = col_number(),
                         injunctions = col_number(),
                         prosecutions = col_number()
                       ))
# view the data
view(flytipping1)


#convert the tibble into a tidy tibble
flytipping_long <- flytipping1 %>% 
  pivot_longer(
  cols = 4:11,
  names_to = "tipping_type",
  values_to = "count"
)

# view the data
view(flytipping_long)



#pivot the tidy tibble into one that is suitable for mapping
flytipping_wide <- flytipping_long %>% 
  pivot_wider(
  id_cols = 1:2,
  names_from = c(year,tipping_type),
  names_sep = "_",
  values_from = count
)


flytipping2 <- flytipping1[,1:4]
widefly <- flytipping2 %>% 
  pivot_wider(
  names_from = year, 
  values_from = total_incidents)
##

```


